# Generated by Django 3.2.24 on 2024-03-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderID',
        ),
    ]
